apiVersion: v1
kind: Service
metadata:
  name: mutator-svc
spec:
  clusterIP: 10.59.240.34
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: event-changer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-mutator
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      app: event-changer
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels: *labels
    spec:
      containers:
        - image: github.com/knative/playground/cmd/event_changer
          name: user-container
          ports:
            - containerPort: 8080
              protocol: TCP
