apiVersion: v1
kind: ConfigMap
metadata:
  name: in-memory-bus-config
  namespace: knative-eventing
data:
  multiChannelFanoutConfig: |
    channelConfigs:
      - namespace: default
        name: c1
        fanoutConfig:
          subscriptions:
            - callableDomain: event-changer.default.svc.cluster.local
              sinkableDomain: message-dumper-bar.default.svc.cluster.local
            - callableDomain: message-dumper-foo.default.svc.cluster.local
            - sinkableDomain: message-dumper-bar.default.svc.cluster.local
      - namespace: default
        name: c2
        fanoutConfig:
          subscriptions: []
      - namespace: other
        name: c3

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventsender
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      app: eventsender
  template:
    metadata:
      labels: *labels
    spec:
      serviceAccountName: feed-sa
      containers:
        - name: eventsender
          image: github.com/knative/playground/cmd/event_sender
        - name: fanout-sidecar
          image: github.com/knative/eventing/cmd/fanoutsidecar
          args: [
            "--sidecar_port=11235",
            "--config_map_noticer=watcher",
          ]
          ports:
            - containerPort: 11235

