apiVersion: v1
kind: ConfigMap
metadata:
  name: fanout-sidecar-config
  namespace: default
data:
  multiChannelFanoutConfig: |
    channelConfigs:
      - namespace: default
        name: c1
        fanoutConfig:
          subscriptions:
            - callableDomain: event-changer.default.svc.cluster.local
              sinkableDomain: message-dumper-bar.default.svc.cluster.local
            - callableDomain: message-dumper-foo.default.svc.cluster.local
            - sinkableDomain: message-dumper-bar.default.svc.cluster.local
      - namespace: default
        name: c2
        fanoutConfig:
          subscriptions:
            - sinkableDomain: message-dumper-foo.default.svc.cluster.local
      - namespace: other
        name: c3
        fanoutConfig:
          subscriptions:
            - sinkableDomain: message-dumper-foo.default.svc.cluster.local

