apiVersion: v1
kind: Pod
metadata:
  annotations:
    sidecar.istio.io/inject: "false"
  labels:
    run: nosidecar
  name: nosidecar
  namespace: default
spec:
  containers:
  - image: harwayne/istioclient
    imagePullPolicy: Always
    name: client
    resources:
      requests:
        cpu: 100m
    stdin: true
    stdinOnce: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    tty: true
  dnsPolicy: ClusterFirst
  restartPolicy: Never

