apiVersion: eventing.knative.dev/v1alpha1
kind: Source
metadata:
  name: source
  namespace: default
spec:
  provisioner:
    ...
  selector:
    matchLabels:
      link-label: source-in

---

apiVersion: eip.eventing.knative.dev/v1alpha1
kind: Link
metadata:
  name: source-link
  namespace: default
  labels:
    link-label: source-in
spec:
  sink:
    apiVersion: eip.eventing.knative.dev/v1alpha1
    kind: TimeAggregator
    name: time-aggregator

---


apiVersion: eip.eventing.knative.dev/v1alpha1
kind: TimeAggregator
metadata:
  name: time-aggregator
  namespace: default
spec:
  fixedWindow: 5m
  aggregateLink: output-link

---


apiVersion: eip.eventing.knative.dev/v1alpha1
kind: Link
metadata:
  name: output-link
  namespace: default
spec:
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: downstream

