apiVersion: eventing.knative.dev/v1alpha1
kind: Source
metadata:
  name: blue-source
  namespace: default
spec:
  provisioner:
    ...
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: blue-source-channel

---

apiVersion: eventing.knative.dev/v1alpha1
kind: Channel
metadata:
  name: blue-source-channel
  namespace: default
spec:
  ...

---

apiVersion: eventing.knative.dev/v1alpha1
kind: Source
metadata:
  name: red-source
  namespace: default
spec:
  provisioner:
    ...
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: red-source-channel

---

apiVersion: eventing.knative.dev/v1alpha1
kind: Channel
metadata:
  name: red-source-channel
  namespace: default
spec:
  ...

---

apiVersion: eventing.knative.dev/v1alpha1
kind: Channel
metadata:
  name: intermediate
  namespace: default
spec:
  ...

---

apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: blue-input
  namespace: default
spec:
  from:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: blue-source-channel
  result:
    target:
      apiVersion: eventing.knative.dev/v1alpha1
      kind: Channel
      name: intermediate

---

apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: red-input
  namespace: default
spec:
  from:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: red-source-channel
  result:
      apiVersion: eventing.knative.dev/v1alpha1
      kind: Channel
      name: intermediate

---

apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: transformer
  namespace: default
spec:
  from:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: intermediate
  call:
    target:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: message-aggregating-function
  result:
    target:
      apiVersion: eventing.knative.dev/v1alpha1
      kind: Channel
      name: downstream

