apiVersion: eventing.knative.dev/v1alpha1
kind: Source
metadata:
  name: source
  namespace: default
spec:
  provisioner:
    ...
  selector:
    matchLabels:
      link-label: source-in

---

apiVersion: eip.eventing.knative.dev/v1alpha1
kind: Link
metadata:
  name: source-link
  namespace: default
  labels:
    link-label: source-in
spec:
  sink:
    apiVersion: eip.eventing.knative.dev/v1alpha1
    kind: Filter
    name: filterer

---

apiVersion: eip.eventing.knative.dev/v1alpha1
kind: Filter
metadata:
  name: filterer
  namespace: default
spec:
  # Returns 2XX to pass the filter, 400 to fail the filter.
  filter:
    target:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: filtering-function
  resultLink: output-link # Name of a Link in the same namespace.

---

apiVersion: eip.eventing.knative.dev/v1alpha1
kind: Link
metadata:
  name: output-link
  namespace: default
spec:
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: downstream

