apiVersion: eventing.knative.dev/v1alpha1
kind: Source
metadata:
  name: source
  namespace: default
spec:
  provisioner:
    ...

---

apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: transformer
  namespace: default
spec:
  from:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Source
    name: source
  call:
    target:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      # Note that this has to be written like a transformer. It either returns the entire event or an empty body, not just true or false.
      name: filtering-function
  result:
    target:
      apiVersion: eventing.knative.dev/v1alpha1
      kind: Channel
      name: downstream

