apiVersion: eventing.knative.dev/v1alpha1
kind: Source
metadata:
  name: source
  namespace: default
spec:
  provisioner:
    ...
  selector:
    matchLabels:
      link-label: source-in

---

apiVersion: eip.eventing.knative.dev/v1alpha1
kind: Link
metadata:
  name: source-link
  namespace: default
  labels:
    link-label: source-in
spec:
  sink:
    apiVersion: eip.eventing.knative.dev/v1alpha1
    kind: Router
    name: router

---

apiVersion: eip.eventing.knative.dev/v1alpha1
kind: Router
metadata:
  name: router
  namespace: default
spec:
  router:
    target:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: routing-function
  # A possible alternative to using a single, well-known location. Allow it to be specified using some language, this example uses JSON Path.
  labelLookup: $.body.foo.bar[0]
  defaultResult: default-result # Name of a Link in the same namespace.
  results:
    red: red-result
    green: green-result

---

apiVersion: eip.eventing.knative.dev/v1alpha1
kind: Link
metadata:
  name: default-result
  namespace: default
spec:
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: default-downstream

---

apiVersion: eip.eventing.knative.dev/v1alpha1
kind: Link
metadata:
  name: red-result
  namespace: default
spec:
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: red-downstream
    
---

apiVersion: eip.eventing.knative.dev/v1alpha1
kind: Link
metadata:
  name: green-result
  namespace: default
spec:
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: green-downstream
