apiVersion: eventing.knative.dev/v1alpha1
kind: Source
metadata:
  name: source
  namespace: default
spec:
  provisioner:
    ...
  selector:
    matchLabels:
      link-label: source-in

---

apiVersion: eip.eventing.knative.dev/v1alpha1
kind: Link
metadata:
  name: source-link
  namespace: default
  labels:
    link-label: source-in
spec:
  sink:
    apiVersion: eip.eventing.knative.dev/v1alpha1
    kind: Transformer
    name: transformer

---

apiVersion: eip.eventing.knative.dev/v1alpha1
kind: Transformer
metadata:
  name: transformer
  namespace: default
spec:
  transformer:
    target:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      # Needs to return multiple messages. Likely talking to Cloud Events and have them support one message containing multiple events.
      name: splitting-function
  resultLink: output-link # Name of a Link in the same namespace.

---

apiVersion: eip.eventing.knative.dev/v1alpha1
kind: Link
metadata:
  name: output-link
  namespace: default
spec:
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: downstream
