apiVersion: eventing.knative.dev/v1alpha1
kind: Source
metadata:
  name: source
  namespace: default
spec:
  provisioner:
    ...
  channel:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: source-channel

---

apiVersion: eventing.knative.dev/v1alpha1
kind: Channel
metadata:
  name: source-channel
  namespace: default
spec:
  ...

---

apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: transformer
  namespace: default
spec:
  from:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Channel
    name: source-channel
  call:
    target:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: transforming-function
  result:
    target:
      apiVersion: eventing.knative.dev/v1alpha1
      kind: Channel
      name: downstream

