apiVersion: eventing.knative.dev/v1alpha1
kind: Source
metadata:
  name: source
  namespace: default
spec:
  provisioner:
    ...

---

apiVersion: eventing.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: transformer
  namespace: default
spec:
  from:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Source
    name: source
  call:
    target:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: transforming-function
  result:
    target:
      apiVersion: eventing.knative.dev/v1alpha1
      kind: Channel
      name: downstream

